### ISSUE TITLE
Users can register, log in, and sign out.

### ISSUE THREAD

**Issue by gino-hong** [gino-hong/final-project#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can register, log in, and sign out.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can register to make their own account. User will able to sign in and out as they please. Having their own account will create a personalized experience for the user.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/96759480/195247617-03d08cf0-5114-4ecd-9c88-1c2f556729df.png)
![image](https://user-images.githubusercontent.com/96759480/195247665-78720287-cef5-4aa0-a162-105c13020f5c.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🐘 Database Tasks

- [x] Update `schema.sql` to build a database of users.
- [x] Update `data.sql` to include an admin user for testing purposes.

### ☁️ Server Tasks

- [x] Update `server/index.js` to handle 'POST' requests for the user to add a username and password.
- [x] Update `server/index.js` to handle 'POST' requests for the user to login with their credentials.
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Create a component to display a form for the user to complete the registration or login process.
- [x] Create a component to send a fetch requests to the server for registration and login.
- [x] Create a component to handle staying signed in and signing out.

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
